# Generated by Django 3.2 on 2024-04-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cake',
        ),
        migrations.AddField(
            model_name='cart',
            name='Cake',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.cake'),
            preserve_default=False,
        ),
    ]
