# Generated by Django 3.2 on 2024-04-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0003_auto_20240426_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cake_customization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweetspot_app.cakecustomization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
