# Generated by Django 3.2 on 2024-05-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.store'),
            preserve_default=False,
        ),
    ]
